{
  config,
  lib,
  ...
}: let
  cfg = config.programs.caelestia-extras.hyprtoolkit;
in {
  config = lib.mkIf cfg.enable {
    xdg.configFile."caelestia/templates/hyprtoolkit.conf".text = ''
      # Generated by Caelestia from the active scheme.
      background = 0xFF{{ background.hex }}
      base = 0xFF{{ surfaceContainer.hex }}
      text = 0xFF{{ onSurface.hex }}
      alternate_base = 0xFF{{ surfaceContainerHigh.hex }}
      bright_text = 0xFF{{ onSurface.hex }}
      accent = 0xFF{{ primary.hex }}
      accent_secondary = 0xFF{{ secondary.hex }}
      icon_theme = Papirus-Dark
      font_family = Sans Serif
      font_family_monospace = CaskaydiaCove NF
      rounding_large = 15
      rounding_small = 8
    '';
  };
}
